export const BlogTypes = {
    SET_LST_BLOGS: 'SET_LST_BLOGS',
    SET_LST_DRAFTS: 'SET_LST_DRAFTS',
    SET_COUNT_BLOGS: 'SET_COUNT_BLOGS',
    SET_TAGS_BLOG: 'SET_TAGS_BLOG',
    SET_BLOG_INFO: 'SET_BLOG_INFO',
    SET_FILENAME: 'SET_FILENAME',
    TOGGLE_SAVE_BOX: 'TOGGLE_SAVE_BOX',
    PROGRESS_UPLOAD: 'PROGRESS_UPLOAD',
    HIDDEN_PROGRESS: 'HIDDEN_PROGRESS'
}